services:
  postgres:
    image: postgres:15
    container_name: workforce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: workforce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d workforce_db"]
      interval: 5s
      retries: 10
      start_period: 5s

  app:
    ports:
      - "8000:8000"
    build:
      context: ./be 
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/workforce_db
    # commend the line below to run test
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
